[package]
name = "ascii-pay-authentication-proxy"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1"
actix-web = { version="3.0.2", features=["rustls"] }
actix-cors = "0.3.0"
tokio = "0.2"
evdev-rs = "0.3"
dotenv = "0.15"
futures = "0.3.5"
url = "1.7"
env_logger = "0.6"
ctrlc = { version = "3.0", features = ["termination"] }
pcsc = "2.3"
byteorder = "1.3"
des = "0.3"
hex-literal = "0.2"
generic-array = "0.12"
rand_core = "0.5"
rand = "0.7"
block-modes = "0.3"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
derive_more = "0.15"
base64 = "0.11"
